# Generated by Django 4.0.4 on 2022-05-19 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('quality', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('displacement', models.IntegerField()),
                ('data_create', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Catch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fish', models.CharField(max_length=40)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PlaceFishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('discriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('addres', models.CharField(max_length=50)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.positions')),
            ],
        ),
        migrations.CreateModel(
            name='FlightHasPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.flight')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.person')),
            ],
        ),
        migrations.CreateModel(
            name='FlightHasCatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.catch')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.flight')),
            ],
        ),
        migrations.CreateModel(
            name='FlightHasBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ban')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.flight')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='bans',
            field=models.ManyToManyField(through='main.FlightHasBan', to='main.ban'),
        ),
        migrations.AddField(
            model_name='flight',
            name='boat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.boat'),
        ),
        migrations.AddField(
            model_name='flight',
            name='catch',
            field=models.ManyToManyField(through='main.FlightHasCatch', to='main.catch'),
        ),
        migrations.AddField(
            model_name='flight',
            name='crew',
            field=models.ManyToManyField(through='main.FlightHasPerson', to='main.person'),
        ),
        migrations.AddField(
            model_name='ban',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.placefishing'),
        ),
    ]
